### ISSUE TITLE
Nova página no iAHx, caso o usuário clique no botão Buscar sem informar uma expressão de busca

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#153]
Com o objetivo de melhorar a experiência do usuário e diminuir a sobrecarga dos servidores, estamos sugerindo que, ao identificar a ação de buscar no iAHx, sem expressão de busca, mandar o usuário para a seguinte página (ainda em mockup).

http://mockups.teste.bireme.org/iahx/zero.php

Requisitos:
- Os filtros desta página devem ter o mesmo funcionamento da coluna de filtros da página de resultados padrão, desta forma se o usuário clicar em "Ver mais" de um determinado filtro será realizado refresh da página.
- A ordem dos filtros será a mesma já definida e apresentada na coluna de filtros, dispensando destta forma a necessidade de configuração adicional.

**Comment by viniciusandrade** [comment]
Encaminhamentos reunião 19/03

- A ordem dos filtros deve seguir a mesma já definida na coluna de filtros exceto pelos filtros de texto completo e intervalo de ano de publicação que devem ser movidas para a segunda linha e ocupar todo o espaço.

- Deve ser criado mecanismo que permita a atualização de uma caixa de filtro (mostrar mais) sem levar em consideração os filtros aplicados nas demais caixas.

**Comment by viniciusandrade** [comment]
Informado pela @pintoros: 

Não consigo combinar nesta interface uma pesquisa na caixa de busca com um ou mais filtros. 

1) Ao digitar os termos na caixa de busca, selecionar o filtro e clicar em filtrar, os termos da caixa de busca são ignorados, aparece só o resultado do filtro
2)  Ao digitar os termos, selecionar o filtro e clicar em buscar, o filtro é ignorado, só aparece o resultado da busca.

**Comment by viniciusandrade** [comment]
@pintoros,
Correções para seus apontamentos aplicadas no ambiente de testes. 
Favor, quando possivel, limpar o cache do navegador e realizar novo teste.
Obrigado.

**Comment by pintoros** [comment]
Teste OK!
Interface funcionando!

Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:d1196ab4-3b81-4478-b6f2-3174a8bcc757]

________________________________
De: viniciusandrade <notifications@github.com>
Enviado: quinta-feira, 2 de abril de 2020 18:07
Para: bireme/iahx-opac <iahx-opac@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/iahx-opac] Nova página no iAHx, caso o usuário clique no botão Buscar sem informar uma expressão de busca (#153)


@pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=02%7C01%7Cpintoros%40paho.org%7C739b79b213e0411f803808d7d749e6e7%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637214584717557346&sdata=t4OI543SDVy3OAIdmBmmAGggGOyQ1FfoBvaa4rcIVs4%3D&reserved=0>,
Correções para seus apontamentos aplicadas no ambiente de testes.
Favor, quando possivel, limpar o cache do navegador e realizar novo teste.
Obrigado.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fiahx-opac%2Fissues%2F153%23issuecomment-608088360&data=02%7C01%7Cpintoros%40paho.org%7C739b79b213e0411f803808d7d749e6e7%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637214584717557346&sdata=JC%2Bb2ZTuWIeGIqD078k5Wtlo0fbc2a%2FoJ3EXeZF80rw%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4AF4HWD4VPHDQRDBOLRKT5CJANCNFSM4LNT6REA&data=02%7C01%7Cpintoros%40paho.org%7C739b79b213e0411f803808d7d749e6e7%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637214584717557346&sdata=uwjGEYHlxhTzPeeWUkFqOlCXR5XIHDdYa%2FfQ5PnxuXE%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
Solicitado pela Verônica alteração do texto para:

A BVS tem uma coleção de 30.098.584 referências de documentos. Clique aqui para ver toda coleção ou faça uma busca aplicando um ou mais dos filtros abaixo.

**Comment by pintoros** [comment]
Nossa, mas com número exato? Muda todos os dias...



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:7f43a482-07c5-47d4-99d9-85395b56359e]

________________________________
De: viniciusandrade <notifications@github.com>
Enviado: sexta-feira, 3 de abril de 2020 11:44
Para: bireme/iahx-opac <iahx-opac@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/iahx-opac] Nova página no iAHx, caso o usuário clique no botão Buscar sem informar uma expressão de busca (#153)


Solicitado pela Verônica alteração do texto para:

A BVS tem uma coleção de 30.098.584 referências de documentos. Clique aqui para ver toda coleção ou faça uma busca aplicando um ou mais dos filtros abaixo.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fiahx-opac%2Fissues%2F153%23issuecomment-608473111&data=02%7C01%7Cpintoros%40paho.org%7C8ec057b86f3f4341138208d7d7dd90a9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637215218931056576&sdata=vXc1BQH%2BacOG04G8K2Uq1%2F%2FWXtSwY9LWjCdRFZMueew%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4FCBD65S7G5CU3NW3LRKXY6FANCNFSM4LNT6REA&data=02%7C01%7Cpintoros%40paho.org%7C8ec057b86f3f4341138208d7d7dd90a9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637215218931066569&sdata=YqAuqUSgb7tSfEh4QFUlW0PwkW%2BRs9gILhxGNG3yjdw%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
Nova página inicial disponível em ambiente de produção.

**Comment by pintoros** [comment]
Informo que faltou incluir a pesquisa DeCS/MeSH nesta página.

Obrigada

**Comment by viniciusandrade** [comment]
Botão "Localizar descritor de assunto" adicionada na página.
