### ISSUE TITLE
Interface Wizard - avaliação e testes

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#206]
Implementação inicial disponível em ambiente de testes. 

Favor, quando possível, realizar os testes e documentar neste issue ajustes necessários.

https://pesquisa.teste.bvsalud.org/portal/

**Comment by pintoros** [comment]
**Interface**
Comentário 1: Achei que polui a interface de busca a pergunta abaixo da caixa de busca. 
Sugestão: Criar aba como havíamos pensado anteriomente. 
Comentário 2: O usuário não tem a dimensão do que vai encontrar adiante. 
Sugestão: A partir da aba criada, mostrar as perguntas de cada etapa, habilitadas conforme usuário evolui na navegação
Comentário 3: Colocar todas as siglas por extenso incluindo a sigla após traço.
Sugestão: Objetivos de Desenvolvimento Sustentável 3 - ODS3
Comentário 4: Colocar os números da meta ou objetivo antes de cada enunciado, conforme tabela de labels enviada em #312 (db-processing).
Comentário 3: Mescla de idiomas (imagem 1)

![wizard1](https://user-images.githubusercontent.com/29313904/91759376-f0308980-eba7-11ea-8d99-7206386c7131.JPG)

**Navegação**
Comentário 1:  A linha de evolução das etapas guarda informação de acordo com a pesquisa anterior (com as próximas opções preenchidas) e permite clic nas etapas sem nenhuma conexão (ver imagem 3)
Sugestão: Cada novo clique na interface, a linha de evolução deve aparecer limpa.

Comentário 2: Nos filtros gerados após a busca que só deu como opção da pergunta 4 o tipo de estudo avaliação, apresenta no resultado mais 2 tipos não selecionados (imagem 2). A sequencia de passos está na linha apresentada na imagem 3.


![wizard3](https://user-images.githubusercontent.com/29313904/91759454-08a0a400-eba8-11ea-9dbd-82d819d6547b.JPG)
![wizard2](https://user-images.githubusercontent.com/29313904/91759461-09d1d100-eba8-11ea-8042-947fb7acaebf.JPG)

**Comment by viniciusandrade** [comment]
@pintoros,

Obrigado pelos seus testes iniciais. O @marcioalvessilva irá trabalhar em ajustes no mockup utilizados para a implementação inicial do wizard para contemplar os comentários 1 e 2 e o @marcoslmori irá realizar os ajustes nas traduções dos comentários 3 e 4.

Relacionado a aplicação dos filtros na interface estamos pensando em alternativas para melhorar o funcionamento.

Abraços

**Comment by marcoslmori** [comment]
**Comentário 3 - Feito**
 Indicar nos idiomas es/en/fr  a sigla utilizada para a ODS3.
Indicar no idioma Frances a sigla de ASSA2030 

**Comentário 4 -  Feito**
Faltando o processamento de  "Meta 3.8 Atingir a cobertura universal de saúde" 
mas já contemplado nos 4 idiomas com o nome logico de  "2_cobertura_universal"

**Comment by pintoros** [comment]
Todos os labels nos 4 idiomas estão na planilha.

Abraço


Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:f743a7ec-2a01-41ef-a591-3b94bfe8e10d]

________________________________
De: Marcos Luis Mori <notifications@github.com>
Enviado: quarta-feira, 2 de setembro de 2020 19:48
Para: bireme/iahx-opac <iahx-opac@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/iahx-opac] Interface Wizard - avaliação e testes (#206)


Comentário 3 - Feito
Indicar nos idiomas es/en/fr a sigla utilizada para a ODS3.
Indicar no idioma Frances a sigla de ASSA2030

Comentário 4 - Feito
Faltando o processamento de "Meta 3.8 Atingir a cobertura universal de saúde"
mas já contemplado nos 4 idiomas com o nome logico de "2_cobertura_universal"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fiahx-opac%2Fissues%2F206%23issuecomment-686067780&data=02%7C01%7Cpintoros%40paho.org%7Cb1a12c0446704c323b0408d84f923f5c%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637346836845881471&sdata=ouOR8rimikQGPGgfOA3oEbHMWiK9LufbZp7Rtk%2BmMfE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4BHODM2B4EQOHCL5ATSD3DSDANCNFSM4QQOYMYQ&data=02%7C01%7Cpintoros%40paho.org%7Cb1a12c0446704c323b0408d84f923f5c%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637346836845891471&sdata=6dI%2BIyHeDnlsGD8OkVzs0kAOdlX8G2o0Ib%2FNZACUaJg%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
@pintoros,

Fiz alguns ajustes para melhorar os itens de navegação que você informou:

Navegação
Comentário 1: A linha de evolução das etapas guarda informação de acordo com a pesquisa anterior (com as próximas opções preenchidas) e permite clic nas etapas sem nenhuma conexão (ver imagem 3)
Sugestão: Cada novo clique na interface, a linha de evolução deve aparecer limpa.

**Ajuste realizado para quando o usuário alterar alguma seleção da pesquisa anterior os passos seguintes são limpos.**

Comentário 2: Nos filtros gerados após a busca que só deu como opção da pergunta 4 o tipo de estudo avaliação, apresenta no resultado mais 2 tipos não selecionados (imagem 2). A sequencia de passos está na linha apresentada na imagem 3.

**Ajuste realizado para limpar os filtros  aplicados na pesquisa anterior para não ter sobreposição de filtros.**

**Comment by viniciusandrade** [comment]
@pintoros,  o @botturam informou que no ambiente de testes somente no período da manhã estão disponíveis todas as bases de dados, no periodo da tarde é realizado processamento e somente MEDLINE fica disponível.

**Comment by marcoslmori** [comment]
atividades efetuadas dos comentários 3 e 4

**Comment by viniciusandrade** [comment]
Issues específicos sendo abertos em https://github.com/bireme/iahx-wizard/
