### ISSUE TITLE
Habilitar opção EVID@Easy no Portal Regional em ambiente de produção

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#241]
- Ajustar configuração
- Ajustar texts.ini em todos os idiomas

**Comment by viniciusandrade** [comment]
@pintoros estamos nos ajustes finais para disponibilização da opção EVID@Easy no Portal Regional e gostaria de solicitar seu apoio para uma rodada extra de testes na interface referente ao funcionamento do wizard e também da coluna de filtros pois foram necessários alterarações no código que podem ter causado algum efeito colateral na funcionamento dos filtros em geral.

Caso não sejam identificados problemas até dia 16/12 estaremos habilitando a opção em produção por isso contamos com seu apoio para nos dar um feedback antes desta data. 

Ambiente de testes:

https://pesquisa.teste.bvsalud.org/portal/

Obrigado

**Comment by pintoros** [comment]
Boa tarde, inclui 2 chamados de condições observadas na navegação nos 3 idiomas.

#246, 247 3e 248

A página de entrada ainda não está habilitada?

Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:07874a12-3884-4ba2-882c-035bfe1af8f1]

________________________________
De: viniciusandrade <notifications@github.com>
Enviado: quinta-feira, 10 de dezembro de 2020 11:13
Para: bireme/iahx-opac <iahx-opac@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/iahx-opac] Habilitar opção EVID@Easy no Portal Regional em ambiente de produção (#241)


@pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=04%7C01%7Cpintoros%40paho.org%7C31a87342eefb4dd6403608d89d15b4b2%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637432063839169702%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ul5T97A%2FfftI7ueuuDxtRhb1L%2BD1vFRw8pOSda2%2Beso%3D&reserved=0> estamos nos ajustes finais para disponibilização da opção EVID@Easy no Portal Regional e gostaria de solicitar seu apoio para uma rodada extra de testes na interface referente ao funcionamento do wizard e também da coluna de filtros pois foram necessários alterarações no código que podem ter causado algum efeito colateral na funcionamento dos filtros em geral.

Caso não sejam identificados problemas até dia 16/12 estaremos habilitando a opção em produção por isso contamos com seu apoio para nos dar um feedback antes desta data.

Ambiente de testes:

https://pesquisa.teste.bvsalud.org/portal/<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpesquisa.teste.bvsalud.org%2Fportal%2F&data=04%7C01%7Cpintoros%40paho.org%7C31a87342eefb4dd6403608d89d15b4b2%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637432063839169702%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q4WabdHwHmcPwYSGUgVmZ8GL%2Ff0bbqFIYDi%2BNggFe6o%3D&reserved=0>

Obrigado

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fiahx-opac%2Fissues%2F241%23issuecomment-742545792&data=04%7C01%7Cpintoros%40paho.org%7C31a87342eefb4dd6403608d89d15b4b2%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637432063839179696%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YnmLn50Z1Vao6c6cVLRpmKfSloiKIO8bMhzJ5SVfrl0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4GM33HXB5KQJIIWD3TSUDJO3ANCNFSM4UJOBXTA&data=04%7C01%7Cpintoros%40paho.org%7C31a87342eefb4dd6403608d89d15b4b2%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637432063839179696%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zCnHV5dxQ%2Bs0KtdURLzO0f8ggSsYvpRrKjUefXgoPus%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
Rose,

Retomando este projeto informo que fiz a revisão dos issues criados e que o Mori está finalizando junto ao ITI a publicação da página de entrada que deve estar disponível no início da próxima semana (08 ou 09/02).

Agradeço, quando possível, validar os issues para prosseguirmos com liberação do recurso.

Obrigado
Vinicius

**Comment by viniciusandrade** [comment]
@pintoros já esta disponível a página de descrição do serviço em ambiente de produção:

https://bvsalud.org/evideasy/pt/

Favor verificar com o @marcoslmori  e @marcioalvessilva  qualquer questão relativa a administração desta página.

Quando estiver OK os textos da página favor informar por aqui para que eu possa disponibilizar o botão do EVID@Easy no Portal de Pesquisa.

Obrigado

**Comment by pintoros** [comment]
@Antonio, Vinicius Andrade (BIR)<mailto:antoniov@paho.org> vou revisar com a Verônica.

Obrigada!



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:fdd15060-a84d-4ee3-86ef-2d2d6a47ce9a]

________________________________
De: viniciusandrade <notifications@github.com>
Enviado: sexta-feira, 5 de fevereiro de 2021 17:40
Para: bireme/iahx-opac <iahx-opac@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/iahx-opac] Habilitar opção EVID@Easy no Portal Regional em ambiente de produção (#241)


@pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=04%7C01%7Cpintoros%40paho.org%7C0955076d38f24851273808d8ca164684%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637481544310137324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=s%2BcQPy84H0uJSJ3CZQV48MtUh8ers7%2BQhmVe6QkSvqI%3D&reserved=0> já esta disponível a página de descrição do serviço em ambiente de produção:

https://bvsalud.org/evideasy/pt/<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbvsalud.org%2Fevideasy%2Fpt%2F&data=04%7C01%7Cpintoros%40paho.org%7C0955076d38f24851273808d8ca164684%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637481544310147331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pyHn2T%2ByV47kFyh0FeaNdkfPzp7deGmdn4A5IeBXBD4%3D&reserved=0>

Favor verificar com o @marcoslmori<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarcoslmori&data=04%7C01%7Cpintoros%40paho.org%7C0955076d38f24851273808d8ca164684%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637481544310147331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kLWIMhUpQVa8GPTCV4OBzustTZ7JmzitxM4cRDxs6bQ%3D&reserved=0> e @marcioalvessilva<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarcioalvessilva&data=04%7C01%7Cpintoros%40paho.org%7C0955076d38f24851273808d8ca164684%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637481544310157316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q6HnKYFA%2F6UkoUJZe4sC%2Bb4bPF7JfnAXq0saWEISLNE%3D&reserved=0> qualquer questão relativa a administração desta página.

Quando estiver OK os textos da página favor informar por aqui para que eu possa disponibilizar o botão do EVID@Easy no Portal de Pesquisa.

Obrigado

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fiahx-opac%2Fissues%2F241%23issuecomment-774276790&data=04%7C01%7Cpintoros%40paho.org%7C0955076d38f24851273808d8ca164684%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637481544310157316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tSNxGPMkjbWcWsk4W0HbMaA4%2BtjGz7ZlybIsssJFtAY%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4AUQKSR6J5RT6KVDATS5RJTZANCNFSM4UJOBXTA&data=04%7C01%7Cpintoros%40paho.org%7C0955076d38f24851273808d8ca164684%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637481544310167311%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FXNHlIzKfCl8ojJhWR1DuH6RV8%2B5fMthvpfhTwCMDBM%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by pintoros** [comment]
Boa noite Vini,

Segue o texto revisado pela Vero e por mim, em português (anexo).

Fiz também a revisão das fontes citadas no final da página.

Corrigir o nome das fontes abaixo:
Peru Nacional para - MINSAPERÚ
Index Psicologia para Periódicos técnico-científicos = Index Psicologia - Periódicos

Faltou incluir as seguintes fontes:
BINACIS
HomeoIndex
MOSAICO - Saúde integrativa
Repositório RHS
Porto Rico
SOF - Segunda Opinião Formativa
BIGG - guias GRADE
PIE




Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:d82778ce-9e34-43ff-bbd1-1dc85b621a35]

________________________________
De: Pinto, Rosemeire (BIR) <pintoros@paho.org>
Enviado: segunda-feira, 8 de fevereiro de 2021 10:46
Para: bireme/iahx-opac <iahx-opac@noreply.github.com>; bireme/iahx-opac <reply@reply.github.com>; Antonio, Vinicius Andrade (BIR) <antoniov@paho.org>
Cc: Mention <mention@noreply.github.com>
Assunto: RE: [bireme/iahx-opac] Habilitar opção EVID@Easy no Portal Regional em ambiente de produção (#241)

@Antonio, Vinicius Andrade (BIR)<mailto:antoniov@paho.org> vou revisar com a Verônica.

Obrigada!



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:fdd15060-a84d-4ee3-86ef-2d2d6a47ce9a]

________________________________
De: viniciusandrade <notifications@github.com>
Enviado: sexta-feira, 5 de fevereiro de 2021 17:40
Para: bireme/iahx-opac <iahx-opac@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/iahx-opac] Habilitar opção EVID@Easy no Portal Regional em ambiente de produção (#241)


@pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=04%7C01%7Cpintoros%40paho.org%7C0955076d38f24851273808d8ca164684%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637481544310137324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=s%2BcQPy84H0uJSJ3CZQV48MtUh8ers7%2BQhmVe6QkSvqI%3D&reserved=0> já esta disponível a página de descrição do serviço em ambiente de produção:

https://bvsalud.org/evideasy/pt/<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbvsalud.org%2Fevideasy%2Fpt%2F&data=04%7C01%7Cpintoros%40paho.org%7C0955076d38f24851273808d8ca164684%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637481544310147331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pyHn2T%2ByV47kFyh0FeaNdkfPzp7deGmdn4A5IeBXBD4%3D&reserved=0>

Favor verificar com o @marcoslmori<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarcoslmori&data=04%7C01%7Cpintoros%40paho.org%7C0955076d38f24851273808d8ca164684%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637481544310147331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kLWIMhUpQVa8GPTCV4OBzustTZ7JmzitxM4cRDxs6bQ%3D&reserved=0> e @marcioalvessilva<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarcioalvessilva&data=04%7C01%7Cpintoros%40paho.org%7C0955076d38f24851273808d8ca164684%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637481544310157316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q6HnKYFA%2F6UkoUJZe4sC%2Bb4bPF7JfnAXq0saWEISLNE%3D&reserved=0> qualquer questão relativa a administração desta página.

Quando estiver OK os textos da página favor informar por aqui para que eu possa disponibilizar o botão do EVID@Easy no Portal de Pesquisa.

Obrigado

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fiahx-opac%2Fissues%2F241%23issuecomment-774276790&data=04%7C01%7Cpintoros%40paho.org%7C0955076d38f24851273808d8ca164684%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637481544310157316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tSNxGPMkjbWcWsk4W0HbMaA4%2BtjGz7ZlybIsssJFtAY%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4AUQKSR6J5RT6KVDATS5RJTZANCNFSM4UJOBXTA&data=04%7C01%7Cpintoros%40paho.org%7C0955076d38f24851273808d8ca164684%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637481544310167311%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FXNHlIzKfCl8ojJhWR1DuH6RV8%2B5fMthvpfhTwCMDBM%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
Oi @pintoros,

Obrigado pela revisão mas informo que eu não tenho acesso a administração desta página. 

A ideia é que você possa realizar os ajustes diretamente pela administração do WordPress deste site. Por favor entre em contato com o @marcoslmori e @marcioalvessilva se tiver dúvidas de como alterar.

Por favor informe por aqui quando finalizado para que eu possa liberar o wizard no Portal de Pesquisa.

Abraços

**Comment by viniciusandrade** [comment]
Botão de opção EVID@Easy habilitada em ambiente de produção.
