### ISSUE TITLE
Add revolvermap script in order to allow users of the website to track in real time the full audience of AIM from the homepage: 

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#301]
```
<script type="text/javascript" src="//ra.revolvermaps.com/0/0/6.js?i=0ytbl2va94f&m=0&s=220&c=ff0000&cr1=ffffff&f=arial&l=0" async="async"></script>
```

**Comment by viniciusandrade** [comment]
This type of resource is not recommended in search page because of a  load and layout impact in the pages. 

Google Analytics provide the real time track for analyze the search page in the administrative area.

**Comment by botturam** [comment]
@viniciusandrade sobre este item, existe uma observação do Mike:

For suggestion: We have understood your explanation regarding the tracker revolvermap ( point 1) . However we are using revolvermap for AIM  because this tool allows us to share efficiently (automatically without processing and/or authentication) website attendance, while the real time track of Google cannot be share directly on live with users without pre-processing or an Google account. Therefore, our suggestion is to try the use of revolvermap under surveillance with website speed metric tools. If the velocity become low with this script , we will remove it; if all thing is normal we will keep it. We hope that our suggestion is receivable.

**Comment by viniciusandrade** [comment]
@botturam favor informar ao usuário:

Unfortunately only Google Analytics is homologated for register and analysis of website use in BIREME websites.
