### ISSUE TITLE
Busca por título abreviado LILACS com resultado vazio

### ISSUE THREAD

**Issue by suelisuga** [bireme/iahx-opac#55]
Prezados,

Informo que títulos abreviados de revistas indexadas em LILACS não estão trazendo os registros no iAHx.

Exemplos: 
Gac. méd. Caracas
Braz. dent,. J

![image](https://user-images.githubusercontent.com/13105683/48015239-beffe300-e10f-11e8-8b2b-ea9af6a2e48d.png)

![image](https://user-images.githubusercontent.com/13105683/48015714-eacf9880-e110-11e8-964d-2b17264c725f.png)

Obrigada
Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by botturam** [comment]
Sueli,

a pesquisa retorna resultado com as seguintes expressões:

ta:"Gac Med Caracas"
ta:"Braz. dent. j. (Online)"

**Comment by botturam** [comment]
Sueli,


a pesquisa retorna resultado com as seguintes expressões:


ta:"Gac Med Caracas"

ta:"Braz. dent. j. (Online)"


abc,


Marcelo Bottura
Supervisor OFI - Operação de Fontes de Informação
BIREME/OPAS/OMS
Departamento de Evidência e Inteligência para a Ação em Saúde
Fone: +55 11 5576-9817
VoIP: 44852
botturam@paho.org<https://mymail.paho.org/owa/redir.aspx?C=yLTqiDx_VECNKWe5PY31-YqMmpHTsdEIesrr2JOQ4xicl2FzzE3bsLP1IxIYKseiLADbwXiIWto.&URL=mailto%3asugasuel%40bireme.ops-oms.org>
________________________________
De: Sueli Mitiko Yano Suga <notifications@github.com>
Enviado: segunda-feira, 5 de novembro de 2018 15:40:00
Para: bireme/iahx-opac
Cc: Subscribed
Assunto: [bireme/iahx-opac] Busca por título abreviado LILACS com resultado vazio (#55)


Prezados,

Informo que títulos abreviados de revistas indexadas em LILACS não estão trazendo os registros no iAHx.

Exemplos:
Gac. méd. Caracas
Braz. dent,. J

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13105683%2F48015239-beffe300-e10f-11e8-8b2b-ea9af6a2e48d.png&data=02%7C01%7Cbotturam%40paho.org%7Cbf0645b8969643a7801908d64345b6ad%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636770364032993033&sdata=MNQbQGMtRpOJmJALGMyNdLauqVFAykL95E08TKJSrak%3D&reserved=0>

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13105683%2F48015714-eacf9880-e110-11e8-964d-2b17264c725f.png&data=02%7C01%7Cbotturam%40paho.org%7Cbf0645b8969643a7801908d64345b6ad%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636770364032993033&sdata=axahUa5RolvBVlhl2vLjhUf3UXvCqlKnwJbNAN57YDI%3D&reserved=0>

Obrigada
Sueli M Yano Suga
BIREME/OPAS/OMS

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fiahx-opac%2Fissues%2F55&data=02%7C01%7Cbotturam%40paho.org%7Cbf0645b8969643a7801908d64345b6ad%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636770364032993033&sdata=9tGimEe7GrYR%2Byyv4T%2FQCaPtHSvPwqEFRLqVKYd%2BiIs%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARkXlzfTBMXlutIb56WwCcw69f95D0xMks5usHfwgaJpZM4YO7Yv&data=02%7C01%7Cbotturam%40paho.org%7Cbf0645b8969643a7801908d64345b6ad%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636770364032993033&sdata=9vTFfqIMH7%2FV%2B2eOcOkNuwDs9%2FvNfgf%2Fpiyikzy5ZG8%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
Sueli,

Eu e o Vinícius fizemos um novo ajuste no processamento do índice de Revista, para desconsiderar "case sensitive", ponto e acentuação.

Creio que agora está perfeito.

**Comment by botturam** [comment]
Por favor, testar em homologação.

**Comment by botturam** [comment]
Sueli,


creio que está perfeito gora.


Por favor, testar em homologação. Amanhã, 4f, estará em produção.


abc,


Marcelo Bottura
Supervisor OFI - Operação de Fontes de Informação
BIREME/OPAS/OMS
Departamento de Evidência e Inteligência para a Ação em Saúde
Fone: +55 11 5576-9817
VoIP: 44852
botturam@paho.org<https://mymail.paho.org/owa/redir.aspx?C=yLTqiDx_VECNKWe5PY31-YqMmpHTsdEIesrr2JOQ4xicl2FzzE3bsLP1IxIYKseiLADbwXiIWto.&URL=mailto%3asugasuel%40bireme.ops-oms.org>
________________________________
De: Sueli Mitiko Yano Suga <notifications@github.com>
Enviado: terça-feira, 6 de novembro de 2018 08:27:40
Para: bireme/iahx-opac
Cc: Bottura, Marcelo (BIR); Comment
Assunto: Re: [bireme/iahx-opac] Busca por título abreviado LILACS com resultado vazio (#55)

Oi Marcelo,
Tudo bem?

Esses títulos abreviados estão diferentes do que está na Title. Tem como recuperar pelo título abreviado LILACS?

Obrigada ??
Sueli

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by botturam** [comment]
Já disponível em produção.
