### ISSUE TITLE
Busca avançada para títulos abreviados de revistas LILACS não trazem resultado

### ISSUE THREAD

**Issue by suelisuga** [bireme/iahx-opac#56]
Prezados,

Informo que na busca avançada do iAHx, quando fazemos a busca por títulos abreviados, o resultado vem negativo.

Exemplos: **Braz. dent. J**

![image](https://user-images.githubusercontent.com/13105683/48015913-59acf180-e111-11e8-8438-1796b855774a.png)
![image](https://user-images.githubusercontent.com/13105683/48016098-d2ac4900-e111-11e8-9de4-88b62fd0e3cd.png)

**J. appl. oral sci**
![image](https://user-images.githubusercontent.com/13105683/48016002-95e05200-e111-11e8-9374-494d43106cf0.png)
![image](https://user-images.githubusercontent.com/13105683/48016053-b90b0180-e111-11e8-9d2a-00006ed8833f.png)

Há outros títulos LILACS com esse mesmo problema.

Obrigada!

Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by botturam** [comment]
Sueli,

Eu e o Vinícius fizemos um novo ajuste no processamento do índice de Revista, para desconsiderar "case sensitive", ponto e acentuação.

Creio que agora está perfeito.

Por favor, testar em homologação.

**Comment by botturam** [comment]
Sueli,


creio que está perfeito gora.


Por favor, testar em homologação. Amanhã, 4f, estará em produção.


abc,


Marcelo Bottura
Supervisor OFI - Operação de Fontes de Informação
BIREME/OPAS/OMS
Departamento de Evidência e Inteligência para a Ação em Saúde
Fone: +55 11 5576-9817
VoIP: 44852
botturam@paho.org<https://mymail.paho.org/owa/redir.aspx?C=yLTqiDx_VECNKWe5PY31-YqMmpHTsdEIesrr2JOQ4xicl2FzzE3bsLP1IxIYKseiLADbwXiIWto.&URL=mailto%3asugasuel%40bireme.ops-oms.org>
________________________________
De: Sueli Mitiko Yano Suga <notifications@github.com>
Enviado: segunda-feira, 5 de novembro de 2018 15:46:56
Para: bireme/iahx-opac
Cc: Subscribed
Assunto: [bireme/iahx-opac] Busca avançada para títulos abreviados de revistas LILACS não trazem resultado (#56)


Prezados,

Informo que na busca avançada do iAHx, quando fazemos a busca por títulos abreviados, o resultado vem negativo.

Exemplos: Braz. dent. J

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13105683%2F48015913-59acf180-e111-11e8-8438-1796b855774a.png&data=02%7C01%7Cbotturam%40paho.org%7C1d7c074bf32d4fbdfeea08d64346ae9f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636770368194204637&sdata=5l6w2X9EYhcYK%2Bjabv1zbDarvSoxyybO4Wp5xySACY8%3D&reserved=0>
[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13105683%2F48016098-d2ac4900-e111-11e8-9de4-88b62fd0e3cd.png&data=02%7C01%7Cbotturam%40paho.org%7C1d7c074bf32d4fbdfeea08d64346ae9f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636770368194204637&sdata=6NtUjLIg%2BHnCgH8fjzWgSQyjpxYvUdIB1MzmkVZR1T0%3D&reserved=0>

J. appl. oral sci
[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13105683%2F48016002-95e05200-e111-11e8-9374-494d43106cf0.png&data=02%7C01%7Cbotturam%40paho.org%7C1d7c074bf32d4fbdfeea08d64346ae9f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636770368194214646&sdata=Js4vP5LElmXU6Pnh0ktK9uEHU6q%2FMkAQN2DnkRPCvjM%3D&reserved=0>
[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13105683%2F48016053-b90b0180-e111-11e8-9d2a-00006ed8833f.png&data=02%7C01%7Cbotturam%40paho.org%7C1d7c074bf32d4fbdfeea08d64346ae9f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636770368194214646&sdata=adaOStJD7nI9eud3MpdqZQNLW6e4ggL7ZeuLQ%2BxphPI%3D&reserved=0>

Há outros títulos LILACS com esse mesmo problema.

Obrigada!

Sueli M Yano Suga
BIREME/OPAS/OMS

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fiahx-opac%2Fissues%2F56&data=02%7C01%7Cbotturam%40paho.org%7C1d7c074bf32d4fbdfeea08d64346ae9f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636770368194224651&sdata=NGyQNrt2Vbspyu7VHtjqMj9OqRZCWKtrqSnP0AX1vcg%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARkXlzDGbMn1W-5JBLwe3TTIn71nQsv2ks5usHmQgaJpZM4YO8HL&data=02%7C01%7Cbotturam%40paho.org%7C1d7c074bf32d4fbdfeea08d64346ae9f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636770368194224651&sdata=PMqzpS33EuYrSYpbEzxvSXn1OqlZZr9zGPC4EyMv8m4%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
Já disponível em produção.
